# Generated by Django 5.1.2 on 2024-10-11 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name": "Quiz", "verbose_name_plural": "Quizzes"},
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="img/category/covers"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="choice",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="choice",
            name="text",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="order_number",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="question",
            name="text",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="description",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default.png",
                null=True,
                upload_to="img/quiz/covers",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Basic"), (1, "Medium"), (2, "Advanced")], default=0
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="result",
            name="count_of_correct_answers",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="quiz.question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.quiz",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="quiz.category",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="quiz.quiz",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
